version: '3.9'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app-frontend
      - /app-frontend/node_modules
    depends_on:
      - backend
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app-backend
      - /app-backend/node_modules
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    restart: 'always'
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
