version: '3.9'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true
    platform: linux/x86_64
    working_dir: /app-frontend
    depends_on:
      - backend
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /app-backend
    depends_on:
      - db
    environment:
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_PORT=3306
  db:
    image: postgres
    container_name: db
    platform: linux/x86_64
    restart: 'always'
    cap_add:
      - SYS_NICE
