version: '3.9'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3000
    working_dir: /app-frontend
    volumes:
      - ./frontend:/app-frontend
    depends_on:
      - backend
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 3001:3001
    working_dir: /app-backend
    volumes:
      - ./backend:/app-backend
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    restart: 'always'
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root